version: 2.1

aliases:
  - &environment
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

  - &restore_cache_dependencies
    name: "Restore dependencies from the cache"
    keys:
      - sbt-dependencies-{{ checksum "build.sbt" }}
      # fallback to using the latest cache if no exact match is found
      - sbt-dependencies-

  - &save_cache_dependencies
    name: "Save dependencies in the cache"
    paths:
      - ~/.m2
      - ~/.ivy2
      - ~/.sbt
      - ~/.cache
    key: sbt-dependencies-{{ checksum "build.sbt" }}

  - &fmt_check
    name: "Check code format"
    command: cat /dev/null | sbt check

  - &export_coverage
    name: "Export code coverage report"
    command: bash <(curl -s https://codecov.io/bash)

commands:
  build_project:
    description: build a sub-project << parameters.project_name >>
    parameters:
      project_name:
        type: string
    steps:
      - run:
          name: Compile code and test code << parameters.project_name >>
          command: cat /dev/null | sbt << parameters.project_name >>/compile << parameters.project_name >>/test:compile
      - run:
          name: Test and compute code coverage << parameters.project_name >>
          command: cat /dev/null | sbt coverage << parameters.project_name >>/test << parameters.project_name >>/coverageReport

jobs:
  build:
    <<: *environment
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: *restore_cache_dependencies
#      - run: *fmt_check
      - build_project:
          project_name: "centrifuge"
      - build_project:
          project_name: "plumbus"
      - build_project:
          project_name: "typedpath"
      - build_project:
          project_name: "fenek"
      - save_cache: *save_cache_dependencies
      - run: *export_coverage
