version: 2.1

aliases:
  - &environment
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

  - &restore_cache_dependencies
    name: "Restore dependencies from the cache"
    keys:
      - sbt-dependencies-{{ checksum "build.sbt" }}
      # fallback to using the latest cache if no exact match is found
      - sbt-dependencies-

  - &update_dependencies
    name: "Update all the dependencies"
    command: cat /dev/null | sbt +update

  - &save_cache_dependencies
    name: "Save dependencies in the cache"
    paths:
      - ~/.m2
      - ~/.ivy2
      - ~/.sbt
      - ~/.cache
    key: sbt-dependencies-{{ checksum "build.sbt" }}

  - &fmt_check
    name: "Check code format"
    command: cat /dev/null | sbt check

  - &export_coverage
    working_directory: ~/repo
    name: "Export code coverage report"
    command: bash <(curl -s https://codecov.io/bash)

  - &prep
    - prepare_deps

  - &all_projects
    - centrifuge
    - fenek
    - typedpath
    - plumbus

commands:
  build_project:
    description: build a sub-project #<< parameters.project_name >>
    parameters:
      project_name:
        type: string
    steps:
      - run:
          name: Compile code and test code << parameters.project_name >>
          command: cat /dev/null | sbt << parameters.project_name >>/compile << parameters.project_name >>/test:compile
      - run:
          name: Test and compute code coverage << parameters.project_name >>
          command: cat /dev/null | sbt coverage << parameters.project_name >>/test << parameters.project_name >>/coverageReport

jobs:
  prepare_deps:
    <<: *environment
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: *restore_cache_dependencies
      - run: *update_dependencies
      - save_cache: *save_cache_dependencies

  centrifuge:
    steps:
      - build_project:
          project_name: centrifuge

  plumbus:
    steps:
      - build_project:
          project_name: plumbus

  typedpath:
    steps:
      - build_project:
          project_name: typedpath

  fenek:
    steps:
      - build_project:
          project_name: fenek

  coverage:
    steps:
      - run: *export_coverage


  workflows:
    version: 2
    jobs:
      - prepare_deps
      - centrifuge:
          requires: *prep
      - typedpath:
          requires: *prep
      - fenek:
          requires:
            - *prep
            - typedpath
      - plumbus:
          requires:
            - *prep
      - coverage:
          require: *all_projects
